---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edge-tweety
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: edge.identiq.com/role
            operator: In
            values:
              - base
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: edge-tweety
    namespace: default
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  volumeMode: Filesystem
  hostPath:
    path: "/data/pv0003/"
    type: DirectoryOrCreate
