# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
stages:
 - clone
 - copy_module_variables
 - docs
 - commit_and_push
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "identiq-protocol/edge-infrastructure"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "codefresh"
    stage: "clone"
  copy_module_variables:
   title: Copy module variables into the example directory
   stage: copy_module_variables
   type: parallel
   steps:
     aws_copy_variables:
       image: alpine:3.14.1
       title: aws
       commands:
         - ls -l
         - cp modules/aws/variables.tf examples/aws/
     azure_copy_variables:
       image: alpine:3.14.1
       title: azure
       commands:
         - cp modules/azure/variables.tf examples/azure/
     gcp_copy_variables:
       image: alpine:3.14.1
       title: gcp
       commands:
         - cp modules/gcp/variables.tf examples/gcp/
  docs:
   title: Generate aws, azure and gcp terraform docs
   stage: docs
   type: parallel
   steps:
     aws_docs:
       image: cytopia/terraform-docs:0.14.1
       title: aws
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/aws
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/aws-docs-header.md --output-file README.md
     azure_docs:
       image: cytopia/terraform-docs:0.14.1
       title: azure
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/azure
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/azure-docs-header.md --output-file README.md
     gcp_docs:
       image: cytopia/terraform-docs:0.14.1
       title: gcp
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/gcp
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/gcp-docs-header.md --output-file README.md
  commit_and_push:
    title: Commit changes and push
    type: git-commit
    stage: "commit_and_push"
    fail_fast: false
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github
      working_directory: '/codefresh/volume/${{CF_REPO_NAME}}'
      commit_message: Automated docs and variables updates
      git_user_name: codefresh-ci
      git_user_email: codefresh@identiq.com
      allow_empty: false
      add:
        - examples/aws/variables.tf
        - examples/azure/variables.tf
        - examples/gcp/variables.tf
        - modules/aws/README.md
        - modules/azure/README.md
        - modules/gcp/README.md

