# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
stages:
 - clone
 - docs
 - check_for_changes
 - commit_and_push
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "identiq-protocol/edge-infrastructure"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "codefresh"
    stage: "clone"
  docs:
   title: Generate aws, azure and gcp terraform docs
   stage: docs
   type: parallel
   steps:
     aws:
       image: cytopia/terraform-docs:0.14.1
       title: aws
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/aws
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/aws-docs-header.md --output-file README.md
     azure:
       image: cytopia/terraform-docs:0.14.1
       title: azure
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/azure
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/azure-docs-header.md --output-file README.md
     gcp:
       image: cytopia/terraform-docs:0.14.1
       title: gcp
       working_directory: /codefresh/volume/${{CF_REPO_NAME}}/modules/gcp
       commands:
         - terraform-docs markdown . --output-mode replace --header-from ../../codefresh/gcp-docs-header.md --output-file README.md
  check_for_changes:
    image: alpine:3.9
    title: Check if docs files has changed
    stage: check_for_changes
    fail_fast: false
    commands:
      - git diff --exit-code modules/aws/README.mda
      - git diff --exit-code modules/azure/README.md
      - git diff --exit-code modules/gcp/README.md
  commit_and_push:
    title: Commit changes and push
    type: git-commit
    stage: "commit_and_push"
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github
      working_directory: '/codefresh/volume/${{CF_REPO_NAME}}'
      commit_message: terraform-docs automated action (aws README.md)
      git_user_name: codefresh-ci
      git_user_email: codefresh@identiq.com
      allow_empty: false
      add:
        - modules/aws/README.md
        - modules/azure/README.md
        - modules/gcp/README.md
      when:
        steps:
          any:
            myTestCondition: steps.check_for_change.result == 'failure'

