{{ if .Values.prometheus.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "helm-operator.fullname" . }}
  labels:
    app: {{ template "helm-operator.name" . }}
    chart: {{ template "helm-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- range $key, $value := .Values.prometheus.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.prometheus.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  endpoints:
  - port: http
    honorLabels: true
    {{- with .Values.prometheus.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.prometheus.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "helm-operator.name" . }}
      release: {{ .Release.Name }}
{{- end }}
