---
- name: Ensure /etc/rancher/rke2 directory exists
  become: true
  file:
    path: /etc/rancher/rke2
    state: directory

- name: Template config.yaml
  template:
    src: config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml

- name: Configure image registry credentials
  template:
    src: registries.yaml.j2
    dest: /etc/rancher/rke2/registries.yaml
