name: Generate terraform docs
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ ci_test ]
  pull_request:
    branches: [ ci_test ]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Copy documentation template files
      uses: canastro/copy-file-action@master
      with:
        source: ".github/templates/docs-aws.md.template"
        target: "modules/aws/README.md"

    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.10.0
      with:
        #working-dir: modules/aws,modules/azure,modules/gcp
        working-dir: modules/aws
        output-file: README.md
        output-method: inject
        git-push: "true"

